dubbo:
  application:
    name: my-project-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181

zookeeper.address: tx1